# Generated by Django 4.0.6 on 2023-03-26 10:42

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='نام و نام خانوادگی')),
                ('time_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نام')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='آیا ادمین است')),
                ('is_active', models.BooleanField(default=True, verbose_name='حساب کاربر فعال است')),
                ('is_staff', models.BooleanField(default=False, verbose_name='اجازه ورود به پنل ادمین')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='آیا سوپر یوزر است')),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=255, null=True, upload_to=account.models.get_profile_image_filepath, verbose_name='تصویر کاربر')),
                ('hide_email', models.BooleanField(default=True, verbose_name='مخفی بودن ایمیل کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='مهارت')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='نام استاد')),
                ('about_teacher', models.TextField(blank=True, null=True, verbose_name='درباره ی استاد')),
                ('linkedin_account', models.URLField(blank=True, max_length=250, null=True, verbose_name='اکانت لینکدین')),
                ('instagram_account', models.URLField(blank=True, max_length=250, null=True, verbose_name='اکانت اینستاگرام')),
                ('website', models.URLField(blank=True, max_length=250, null=True, verbose_name='آدرس وب سایت')),
                ('twitter_account', models.URLField(blank=True, max_length=250, null=True, verbose_name='اکانت توتیتر')),
                ('stackoverflow_account', models.URLField(blank=True, max_length=250, null=True, verbose_name='اکانت استک آورفلو')),
                ('skills', models.ManyToManyField(blank=True, to='account.skill', verbose_name='مهارت های استاد')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='استاد مربوطه')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'استاتید',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='داتشجو')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجویان',
            },
        ),
    ]
