# Generated by Django 4.0.6 on 2022-09-14 18:29

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='time_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نام'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='hide_email',
            field=models.BooleanField(default=True, verbose_name='مخفی بودن ایمیل کاربر'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='حساب کاربر فعال است'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='آیا ادمین است'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='اجازه ورود به پنل ادمین'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='آیا سوپر یوزر است'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=255, null=True, upload_to=account.models.get_profile_image_filepath, verbose_name='تصویر کاربر'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about_teacher',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ی استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='instagram_account',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='اکانت اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='linkedin_account',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='اکانت لینکدین'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.ManyToManyField(blank=True, to='account.skill', verbose_name='مهارت های استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='stackoverflow_account',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='اکانت استک آورفلو'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='استاد مربوطه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=100, verbose_name='نام استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='twitter_account',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='اکانت توتیتر'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='آدرس وب سایت'),
        ),
    ]
