# Generated by Django 4.0.6 on 2022-09-22 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_time_joined_alter_account_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'دانشجو', 'verbose_name_plural': 'دانشجویان'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'استاد', 'verbose_name_plural': 'استاتید'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='مهارت'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='داتشجو'),
        ),
    ]
