# Generated by Django 4.0.6 on 2022-08-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_skill_teacher_about_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='teacher_name',
        ),
    ]
