# Generated by Django 4.0.6 on 2022-08-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_username_teacher_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.ManyToManyField(blank=True, to='account.skill'),
        ),
    ]
