# Generated by Django 4.0.6 on 2022-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_content',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
