# Generated by Django 4.0.6 on 2022-09-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'بخش نظرات'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'ویدیو', 'verbose_name_plural': 'بخش ویدیو ها'},
        ),
    ]
