# Generated by Django 4.0.6 on 2022-08-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration_video',
            field=models.IntegerField(null=True, verbose_name='زمان ویدیو'),
        ),
    ]
