# Generated by Django 4.0.6 on 2022-08-26 17:49

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_video_duration_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration_video',
            field=models.CharField(default=1, max_length=20, verbose_name='تایم ویدیو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default=1, upload_to=course.models.get_video_filepath, verbose_name=' ویدیو دوره '),
            preserve_default=False,
        ),
    ]
