# Generated by Django 4.0.6 on 2022-08-10 19:49

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
        ('course', '0005_alter_course_category_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': ('نظر',), 'verbose_name_plural': 'بخش نظرات'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': ('دوره',), 'verbose_name_plural': ' دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': ('ویدیو',), 'verbose_name_plural': 'بخش ویدیو ها'},
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' کاربر مربوط '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name=' نظرهات '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name=' دوره مرتبط '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ ایجاد '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=' وضعیت فعال بودن '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name=' تاریخ آپدیت '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('readed', 'readed'), ('unreaded', 'unreaded'), ('close', 'close')], max_length=25, verbose_name=' وضعیت پیام '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_ip',
            field=models.CharField(blank=True, max_length=20, verbose_name=' آی پی کاربر '),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name=' دسته بندی '),
        ),
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ ایجاد '),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=' توضیحات '),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default=course.models.get_default_course_image, null=True, upload_to=course.models.get_course_image_filepath, verbose_name='تصویر دوره '),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعال بودن دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='رایگان '),
        ),
        migrations.AlterField(
            model_name='course',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name=' تاریخ آپدیت '),
        ),
        migrations.AlterField(
            model_name='course',
            name='sell_count',
            field=models.IntegerField(blank=True, null=True, verbose_name=' تعداد فروش '),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name=' آدرس اسلاگ '),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(blank=True, choices=[('New Course', 'New Course'), ('Course in progress', 'Course in progress'), ('Course update', 'Course update'), ('The course is over', 'The course is over')], max_length=25, verbose_name=' وضعیت '),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' مدرس دوره '),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name=' عنوان '),
        ),
        migrations.AlterField(
            model_name='course',
            name='view_count',
            field=models.IntegerField(blank=True, null=True, verbose_name=' تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='دوره مرتبط'),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ ایجاد '),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=' توضیحات '),
        ),
        migrations.AlterField(
            model_name='video',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name=' تاریخ آپدیت '),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name=' آدرس اسلاگ '),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name=' عنوان '),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=course.models.get_video_filepath, verbose_name=' ویدیو دوره '),
        ),
    ]
