# Generated by Django 4.0.6 on 2022-08-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_comment_options_alter_course_options_and_more'),
        ('course', '0006_course_price'),
    ]

    operations = [
    ]
