# Generated by Django 4.0.6 on 2022-09-01 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('order_note', models.CharField(blank=True, max_length=150, null=True, verbose_name='توضیحات سفارش')),
                ('order_total', models.FloatField(blank=True, null=True, verbose_name='جمع سفارش')),
                ('status', models.CharField(choices=[('New', 'جدید'), ('Accepted', 'تایید شده'), ('Completed', 'تکمیل شده'), ('Cancelled', 'کنسل شده')], default='New', max_length=15, verbose_name='وضعیت سفارش')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='آی پی کاربر ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده است  ')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت ')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='یوزر سفارش دهنده')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش محصول')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='دوره مورد نظر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='سفارش مربوط')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_qyt', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
