# Generated by Django 4.0.6 on 2022-08-26 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'لیست سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'سفارش محصول', 'verbose_name_plural': 'محصولات سفارش داده شده'},
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر سفارش دهنده'),
        ),
    ]
