# Generated by Django 4.0.6 on 2022-09-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_price_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='tracking_code',
        ),
    ]
