# Generated by Django 4.0.6 on 2022-08-23 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=100, verbose_name='آیدی پرداخت ')),
                ('payment_method', models.CharField(max_length=100, verbose_name='روش پرداخت ')),
                ('amount_paid', models.CharField(max_length=100, verbose_name='مبلغ پرداخت شده ')),
                ('status', models.CharField(max_length=100, verbose_name='وضعیت پرداخت ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='یوز پرداخت کننده ')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'بخش پرداخت ها ',
            },
        ),
    ]
