# Generated by Django 4.0.6 on 2022-08-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'لیست پرداخت ها '},
        ),
    ]
